# Generated by Django 3.2 on 2021-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=5)),
                ('nationality', models.CharField(max_length=30)),
                ('freelance', models.CharField(default='Available', max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('skype', models.CharField(max_length=30)),
                ('languages', models.CharField(max_length=30)),
            ],
        ),
    ]
