# Generated by Django 3.2 on 2021-04-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=30)),
                ('your_email', models.CharField(max_length=30)),
                ('your_subject', models.CharField(max_length=30)),
                ('your_message', models.TextField()),
            ],
        ),
    ]
